### ISSUE TITLE
".bitmap is auto-generated"

### ISSUE THREAD

**Issue by itaymendel** [teambit/docs#13]
the sentence "This file is auto-generated by Bit, but should be committed to the Version Control tool". When referring to the `.bitmap` file can be misleading.

While it is not a completely false statement, the file is not autogenerated, but more of a way to log the developer's decisions about which are the imported components, their location and version.

It is 'auto-generated' in the same sense the `package-lock.json` is autogenerated. True, a tool creates and manages it for any operation, however - it describes the exact state of the component index that got generated.

The key difference here is that there's no way for Bit to re-generate it automatically.

**Comment by Tallyb** [comment]
next time link to the docs...
