### ISSUE TITLE
Overrides of files/dirs is not documented

### ISSUE THREAD

**Issue by davidfirst** [teambit/docs#17]
a user can ignore a file so then Bit won't search for it and ask to track it. 
For this, the prefix `file://` must be added to the file path.
I don't see this in the docs.
Thanks @zeesulehria  for reporting this.

**Comment by GiladShoham** [comment]
This feature will tell bit to ignore actual requires to specific files when calculating the dependencies.
It is also support globs.
Examples:
```js
// comp1.js
require('../comp2')

// config (inside overrides)
comp1: {
  dependencies: {
    // ignoring comp2 dependency
    [file://comp2.js]: '-'
  }
}
```

```js
// comp1.js
require('../utils/sort')
require('../utils/get')
require('../utils/unique')

// config (inside overrides)
comp1: {
  dependencies: {
    // Ignoring all utils dependencies
    [file://utils/*]: '-'
  }
}
```

examples from e2e:
https://github.com/teambit/bit/blob/master/e2e/functionalities/workspace-config.e2e.3.js#L182
https://github.com/teambit/bit/blob/master/e2e/flows/pad-left-and-is-string.e2e.3.js#L445
