### ISSUE TITLE
Import entire collection docs

### ISSUE THREAD

**Issue by wjramos** [teambit/docs#26]
in `sourcing-components`, the docs state that you can import an entire collection with a glob pattern as `import <user>.<collection>/*`. 

Doing this in zsh, you receive the error `zsh: no matches found: <user>.<collection>/*`

The example URL should be quoted to escape the url - this took far longer than desired to figure out why this was not working as expected

**Comment by Tallyb** [comment]
Hi, 
Thanks. I will update it in the doc. 
Note that it already exist if you do bit import --help.
