### ISSUE TITLE
error at apis/cli.md in the bit add section

### ISSUE THREAD

**Issue by philipszdavido** [teambit/docs#31]
The bit add command section at apis/cli.md has a little error.

**Comment by philipszdavido** [comment]
In https://github.com/teambit/docs/blob/master/docs/apis/cli.md, at the section **Tracking a component for each file in each sub-directory**, It said:

> You can track multiple components for each sub-directory.
> 
> `bit add src/**/*`
> 
> This will create a component for each of the files in src and in its sub-directories. For example, let's say this is our file structure:
> 
> └───src
>     └───one
>         └───first.js
>         └───second.js
>     └───two
>         └───third.js
>     └───fourth.js
> 
> The components created will be: `first`, `second`, `third`, `fourth`.

I recreated the Node project in my machine and ran the command. Only the components of the files at the sub-dirs of `src` were tracked: `first`, `second` and `third`. No `fourth`.

`fourth` shouldn't be created because the command will only track files inside the sub-dirs of `src` and `fourth` is a file inside `src` not a sub-dir.

See my `.bitmap`:

```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

{
    "first": {
        "files": [
            {
                "relativePath": "src/one/first.js",
                "test": false,
                "name": "first.js"
            }
        ],
        "mainFile": "src/one/first.js",
        "origin": "AUTHORED",
        "exported": false
    },
    "second": {
        "files": [
            {
                "relativePath": "src/one/second.js",
                "test": false,
                "name": "second.js"
            }
        ],
        "mainFile": "src/one/second.js",
        "origin": "AUTHORED",
        "exported": false
    },
    "third": {
        "files": [
            {
                "relativePath": "src/two/third.js",
                "test": false,
                "name": "third.js"
            }
        ],
        "mainFile": "src/two/third.js",
        "origin": "AUTHORED",
        "exported": false
    },
    "version": "14.4.3"
}
```

**Comment by Tallyb** [comment]
this document is obsolete, removed
