### ISSUE TITLE
differences in using glob patterns should be added

### ISSUE THREAD

**Issue by philipszdavido** [teambit/docs#33]
The glob patterns are quite tricky if not well understood. So I think the differences in using them with bit commands should be clearly stated.

For example:

```
bit add src/**
```
is not the same as:

```
bit add src/**/
```

They will yield different results

**Comment by itaymendel** [comment]
so what you think is that we should add some tips and gotchas about glob-patterns?
at the moment we haven't thought about tackling it as this is not specifically around Bit, but I assume we can lowkey write about it.

**Comment by philipszdavido** [comment]
Yes, I  think more tips and infos should be given about it. Most devs wouldn't want to work one components one after another,  they would like to work on as many components  at once and glob patterns help with that. I have one commenter in my post asking me that he has over 50 components and how to add all of them at once using Bit. See? the glob pattern will come to rescue.

Yes,  they are not around Bit, but Bit uses them to aggregate and work on more than one component at a time. They are beneficial to Bit and devs using Bit,  so they should be treated as a topic.

**Comment by philipszdavido** [comment]
I can write about it for you. If don't mind

**Comment by Tallyb** [comment]
A PR would be great!

**Comment by debs-obrien** [comment]
closing this pr as new docs just merged for Harmony https://harmony-docs.bit.dev/

if you see anything missing on this just let us know. thanks
