### ISSUE TITLE
error at docs/cli.md

### ISSUE THREAD

**Issue by philipszdavido** [teambit/docs#34]
Section **Tracking a single directory as multiple components** in https://github.com/teambit/docs/blob/master/docs/apis/cli.md said:

> You can use glob pattern to track a single directory as multiple components.
> 
> `bit add src/foo/*`
> 
> This will create as many components as there are files inside the directory, all with `foo` as their namespace. For example, if `foo` directory contains two files - `bar.js` and `second.js`, two components will be created: `bar` and `second`.

I tried the command, it didn't create `bar` and `second` components with `foo` as their namespaces. It created them as standalone components.

See my `.bitmap`:

```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

{
    "bar": {
        "files": [
            {
                "relativePath": "src/foo/bar.js",
                "test": false,
                "name": "bar.js"
            }
        ],
        "mainFile": "src/foo/bar.js",
        "origin": "AUTHORED",
        "exported": false
    },
    "second": {
        "files": [
            {
                "relativePath": "src/foo/second.js",
                "test": false,
                "name": "second.js"
            }
        ],
        "mainFile": "src/foo/second.js",
        "origin": "AUTHORED",
        "exported": false
    },
    "version": "14.4.3"
}
```

With this I tried using `foo/*` to perform actions on the `bar` and `second` components at once, it didn't work.

So, I think the command only creates components from all the files inside the specified folder without making namespaces out of the folder name.

**Comment by Tallyb** [comment]
Doc is outdated. removed.
