### ISSUE TITLE
glob pattern error at apis/cli.md

### ISSUE THREAD

**Issue by philipszdavido** [teambit/docs#35]
Section **Tracking a component for each sub-directory** in https://github.com/teambit/docs/blob/master/docs/apis/cli.md said:

> You can use glob pattern to track a each sub-directory as a component.
> 
> `bit add src/**/`
> 
> This will create a component for each of src's sub-directories (and files). For example, let's say this is our file structure:
> 
> └───src
>     └───one
>         └───index.js
>     └───two
>         └───index.js
>     └───single.js
> 
> The components created will be: `single`, `one`, `two`.
> 

I think, only components: `one` and `two` should be created. `single` shouldn't be created because `single.js` is a file in `src` not a directory. 

See my `.bitmap`:

```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

{
    "one": {
        "files": [
            {
                "relativePath": "src/one/index.js",
                "test": false,
                "name": "index.js"
            }
        ],
        "mainFile": "src/one/index.js",
        "trackDir": "src/one",
        "origin": "AUTHORED",
        "exported": false
    },
    "two": {
        "files": [
            {
                "relativePath": "src/two/index.js",
                "test": false,
                "name": "index.js"
            }
        ],
        "mainFile": "src/two/index.js",
        "trackDir": "src/two",
        "origin": "AUTHORED",
        "exported": false
    },
    "version": "14.4.3"
}
```

That means `bit add YOUR_FOLDER/**/` will create components from the sub-dirs of YOUR_FOLDER excluding the files in the YOUR_FOLDER folder.

**Comment by Tallyb** [comment]
This document is no longer relevant
