### ISSUE TITLE
docs ci section is missing a `bit link` step

### ISSUE THREAD

**Issue by odedre** [teambit/docs#48]
here:
https://docs.bit.dev/docs/ci

we should have another step in this section:

![Screen Shot 2020-02-13 at 4 23 15 PM](https://user-images.githubusercontent.com/15064762/74444285-514b7680-4e7d-11ea-8236-5ce82cb5beb1.png)

**Comment by Tallyb** [comment]
@GiladShoham  - is that required?

**Comment by itaymendel** [comment]
`bit import` handles linking for each component automatically, no need in other commands.
