### ISSUE TITLE
the centralized library workflow image in docs/workflows.md is broken

### ISSUE THREAD

**Issue by cascandaliato** [teambit/docs#67]
The workflow image in [docs/workflows.md](https://github.com/teambit/docs/blob/master/docs/workflows.md) doesn't show up:

```markdown
![Centralized library workflow](https://storage.googleapis.com/static.bit.dev/docs/images/workflow_central.png)
```

![image](https://user-images.githubusercontent.com/8927157/89785614-f8eaee00-db1a-11ea-9847-8036fe0fcbc5.png)

Another broken image in the same page:
![image](https://user-images.githubusercontent.com/8927157/89785981-7f073480-db1b-11ea-8c24-f7a263a668ea.png)

**Comment by debs-obrien** [comment]
closing this pr as new docs just merged for Harmony https://harmony-docs.bit.dev/
