### ISSUE TITLE
New docs - Tutorial page (02-quick-start)

### ISSUE THREAD

**Issue by benjgil** [teambit/docs#74]
/docs/getting-started/quick-start#add-tests
- Where did we talk about using an environment extension before?

/docs/getting-started/quick-start#add-live-examples
 - Need to go over the whole examples section - not clear what the inputs are, what scope means, and no idea where Card component came from...

**Comment by debs-obrien** [comment]
closing this pr as new docs just merged for Harmony https://harmony-docs.bit.dev/
